routes:
  - hello-nodejs.main
  - hello-nodejs.main_long_timeout
hostnames:
  - hello-nodejs-extra.easysolution.work
  - hello-nodejs-ultra-extra.easysolution.work
traffic:
  provider: istio
  ejectUnhealthy: false
  latencyAware: true

singleton: true
maxDown: 1
