repo: https://github.com/Murad-Suleymanov/hello-csharp
hpa:
  minReplicas: 2
  maxReplicas: 3
resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 250Mi
    cpu: 150m

traffic:
  rateLimit:
    enabled: true
    mode: local
    local:
      requestsPerSecond: 100
      burst: 20

readinessProbe:
  path: /Health

livenessProbe:
  path: /Health
