main:
  hostnames:
    - hello-python-extra.easysolution.work
    - hello-python-ultra-extra.easysolution.work
    
  hpa:
    minReplicas: 1
    maxReplicas: 1
    targetRPS: 100
    window: 15m
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 250Mi
      cpu: 150m

  traffic:
    rateLimit:
      enabled: true
      mode: local
      local:
        requestsPerSecond: 100
        burst: 20

  canary:
    enabled: true
    weight: 10
