repo: https://github.com/Murad-Suleymanov/hello-python
hpa:
  minReplicas: 1
  maxReplicas: 2
resources:
  requests:
    memory: 200Mi
    cpu: 100m
  limits:
    memory: 250Mi
    cpu: 150m

traffic:
  rateLimit:
    enabled: true
    mode: local
    local:
      requestsPerSecond: 100
      burst: 20

canary:
  enabled: true
  weight: 10
